"""Core HTTP Client <>4C;8."""

from .config import (
    TimeoutConfig,
    RetryConfig,
    ConnectionPoolConfig,
    SecurityConfig,
    HTTPClientConfig,
)
from .exceptions import (
    HTTPClientException,
    TemporaryError,
    FatalError,
    NetworkError,
    TimeoutError,
    ConnectionError,
    ProxyError,
    DNSError,
    ServerError,
    TooManyRequestsError,
    HTTPError,
    BadRequestError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    InvalidResponseError,
    ResponseTooLargeError,
    DecompressionBombError,
    TooManyRetriesError,
    ConfigurationError,
    classify_requests_exception,
)

__all__ = [
    # Config
    "TimeoutConfig",
    "RetryConfig",
    "ConnectionPoolConfig",
    "SecurityConfig",
    "HTTPClientConfig",
    # Exceptions
    "HTTPClientException",
    "TemporaryError",
    "FatalError",
    "NetworkError",
    "TimeoutError",
    "ConnectionError",
    "ProxyError",
    "DNSError",
    "ServerError",
    "TooManyRequestsError",
    "HTTPError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "InvalidResponseError",
    "ResponseTooLargeError",
    "DecompressionBombError",
    "TooManyRetriesError",
    "ConfigurationError",
    "classify_requests_exception",
]
